// <auto-generated />
using System;
using AlphaFleet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaFleet.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407124627_UpdateShipSeedData")]
    partial class UpdateShipSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlphaFleet.Data.Models.Admiral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FleetId")
                        .IsUnique();

                    b.ToTable("Admirals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99d05329-8efe-42b1-8d7e-aed411921502"),
                            Bio = "A veteran of the Sol Campaigns, Marcus Varro has commanded Alpha Fleet since its inception. Known for his tactical brilliance and unwavering composure under fire, he transformed a ragtag patrol group into the most decorated fleet in the sector.",
                            FirstName = "Marcus",
                            FleetId = new Guid("c8b02d34-76f8-4dbd-942e-2d680d5b84ef"),
                            ImageUrl = "/images/admirals/varro.jpg",
                            LastName = "Varro",
                            Rank = 3
                        },
                        new
                        {
                            Id = new Guid("3aebb0e2-4ec1-460d-aa0c-81ada509f2e8"),
                            Bio = "Elena Krieger rose through the ranks after the Battle of Orion Outpost, where she single-handedly coordinated the defense of three stations simultaneously. Her aggressive tactics and quick decision-making earned her command of Beta Squadron.",
                            FirstName = "Elena",
                            FleetId = new Guid("4241c74f-092c-4249-b731-954fb7658830"),
                            ImageUrl = "/images/admirals/krieger.jpg",
                            LastName = "Krieger",
                            Rank = 1
                        },
                        new
                        {
                            Id = new Guid("f510dfdb-07f8-4788-9b02-cec3cb7f9e26"),
                            Bio = "Idris Okonkwo is a strategist who prefers diplomacy over direct confrontation. His leadership of Gamma Wing has kept the Vega Station corridor open for trade during some of the most turbulent periods in recent memory.",
                            FirstName = "Idris",
                            FleetId = new Guid("86634405-36a8-4727-93bd-97273e947361"),
                            ImageUrl = "/images/admirals/okonkwo.jpg",
                            LastName = "Okonkwo",
                            Rank = 2
                        },
                        new
                        {
                            Id = new Guid("d34671ee-08b7-42f4-9e58-bd03298ba489"),
                            Bio = "The youngest flag officer in the fleet, Yuki Tanaka was promoted after her daring rescue of the civilian convoy near Centauri Reach. She now commands Delta Fleet with a focus on exploration and humanitarian operations.",
                            FirstName = "Yuki",
                            FleetId = new Guid("e40fcb34-fda4-4f52-889b-996b0040a7ce"),
                            ImageUrl = "/images/admirals/tanaka.jpg",
                            LastName = "Tanaka",
                            Rank = 0
                        },
                        new
                        {
                            Id = new Guid("e7f9adaa-f6ba-4d6d-a560-d383ef9dda3e"),
                            Bio = "Grand Admiral Volkov is the supreme commander overseeing all fleet operations. A former fighter pilot turned tactician, he earned the highest rank after orchestrating the decisive victory at the Siege of Sirius Gate. His word is law across every division.",
                            FirstName = "Aleksei",
                            FleetId = new Guid("44dee55a-f48f-419f-884b-943355bbde32"),
                            ImageUrl = "/images/admirals/volkov.jpg",
                            LastName = "Volkov",
                            Rank = 4
                        },
                        new
                        {
                            Id = new Guid("b7c3d8a1-5e4f-4a92-8d16-7f3b2c9e1d04"),
                            Bio = "Nadia Reyes is a former intelligence officer who transitioned to fleet command after uncovering a pirate syndicate in the Andromeda corridor. Her sharp instincts and network of informants make Zeta Patrol the most well-informed unit in the navy.",
                            FirstName = "Nadia",
                            FleetId = new Guid("c8186cc3-573a-411b-b2d7-a5fd40b9beaf"),
                            ImageUrl = "/images/admirals/reyes.jpg",
                            LastName = "Reyes",
                            Rank = 2
                        },
                        new
                        {
                            Id = new Guid("4e8a1f6c-d293-47b5-a81e-9c5f0e7d2a38"),
                            Bio = "Henrik Stålberg is a logistics genius who keeps the supply lines running no matter the circumstances. Under his command, Eta Convoy has never lost a single cargo shipment, earning him the nickname 'The Unbreakable Chain'.",
                            FirstName = "Henrik",
                            FleetId = new Guid("9ddf8528-35eb-433f-8486-29fc4123f4ff"),
                            ImageUrl = "/images/admirals/stalberg.jpg",
                            LastName = "Stålberg",
                            Rank = 0
                        },
                        new
                        {
                            Id = new Guid("a2d9c7e5-1b84-4f63-90ae-6d8b3f5c4e17"),
                            Bio = "Vice Admiral Sharma is a decorated combat pilot who flew over 300 sorties before taking command of Theta Squadron. Her hands-on leadership style and refusal to send her crews anywhere she wouldn't go herself have earned her fierce loyalty.",
                            FirstName = "Priya",
                            FleetId = new Guid("596dc552-0964-4298-baa7-34bee5b255b3"),
                            ImageUrl = "/images/admirals/sharma.jpg",
                            LastName = "Sharma",
                            Rank = 1
                        },
                        new
                        {
                            Id = new Guid("6f1e4b8d-c5a2-49d7-b3f0-8e2d7a9c6b51"),
                            Bio = "Fleet Admiral Mensah is a visionary who championed the construction of Laniakea Hub as a forward operating base. His bold expansionist strategy doubled the navy's operational range and opened new territories for exploration.",
                            FirstName = "Kofi",
                            FleetId = new Guid("6c6294c1-d329-4240-9620-d4bebed89fd3"),
                            ImageUrl = "/images/admirals/mensah.jpg",
                            LastName = "Mensah",
                            Rank = 3
                        },
                        new
                        {
                            Id = new Guid("c8d3a5f2-7e19-4b06-a4d8-1f9e6c3b5d72"),
                            Bio = "Admiral Petrov commands Kappa Division from the remote Orpheus Station, where he oversees deep-space patrol and border defense. A master of asymmetric warfare, she has repelled incursions from forces ten times her fleet's size.",
                            FirstName = "Svetlana",
                            FleetId = new Guid("1ad72291-5fa1-4744-9db8-19a382b269fd"),
                            ImageUrl = "/images/admirals/petrov.jpg",
                            LastName = "Petrov",
                            Rank = 2
                        });
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Faction")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttackingFleetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DamageDealt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("DefendingFleetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefendingStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurnsPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AttackingFleetId");

                    b.HasIndex("DefendingFleetId");

                    b.HasIndex("DefendingStationId");

                    b.ToTable("Battles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1e2d3c4-b5a6-7890-1234-56789abcdef0"),
                            AttackingFleetId = new Guid("c8b02d34-76f8-4dbd-942e-2d680d5b84ef"),
                            DamageDealt = 2500,
                            DefendingFleetId = new Guid("4241c74f-092c-4249-b731-954fb7658830"),
                            DefendingStationId = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            Description = "Alpha Fleet successfully captured Orion Outpost.",
                            EndTime = new DateTime(2026, 4, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            Outcome = 1,
                            StartTime = new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            TurnsPlayed = 3
                        });
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.BattleTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("DefenderRemainingHealth")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.ToTable("BattleTurns");
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fleets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8b02d34-76f8-4dbd-942e-2d680d5b84ef"),
                            Location = "Sol System",
                            Name = "Alpha Fleet"
                        },
                        new
                        {
                            Id = new Guid("4241c74f-092c-4249-b731-954fb7658830"),
                            Location = "Orion Outpost",
                            Name = "Beta Squadron"
                        },
                        new
                        {
                            Id = new Guid("86634405-36a8-4727-93bd-97273e947361"),
                            Location = "Vega Station",
                            Name = "Gamma Wing"
                        },
                        new
                        {
                            Id = new Guid("e40fcb34-fda4-4f52-889b-996b0040a7ce"),
                            Location = "Centauri Reach",
                            Name = "Delta Fleet"
                        },
                        new
                        {
                            Id = new Guid("44dee55a-f48f-419f-884b-943355bbde32"),
                            Location = "Sirius Gate",
                            Name = "Epsilon Armada"
                        },
                        new
                        {
                            Id = new Guid("c8186cc3-573a-411b-b2d7-a5fd40b9beaf"),
                            Location = "Andromeda Port",
                            Name = "Zeta Patrol"
                        },
                        new
                        {
                            Id = new Guid("9ddf8528-35eb-433f-8486-29fc4123f4ff"),
                            Location = "Tau Outpost",
                            Name = "Eta Convoy"
                        },
                        new
                        {
                            Id = new Guid("596dc552-0964-4298-baa7-34bee5b255b3"),
                            Location = "Delta Quadrant",
                            Name = "Theta Squadron"
                        },
                        new
                        {
                            Id = new Guid("6c6294c1-d329-4240-9620-d4bebed89fd3"),
                            Location = "Laniakea Hub",
                            Name = "Iota Fleet"
                        },
                        new
                        {
                            Id = new Guid("1ad72291-5fa1-4744-9db8-19a382b269fd"),
                            Location = "Orpheus Station",
                            Name = "Kappa Division"
                        });
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("ShipHullClass")
                        .HasColumnType("int");

                    b.Property<int>("ShipProductionYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("Ships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7d4e8a2-5c19-4b7e-9f21-a8c3b6d1e9f4"),
                            Attack = 11,
                            Class = "Fighter",
                            Defense = 1,
                            FleetId = new Guid("c8b02d34-76f8-4dbd-942e-2d680d5b84ef"),
                            Health = 55,
                            History = "The Sparrow is the most mass-produced fighter in the Sol Defence Force. Cheap, fast, and expendable, entire wings of Sparrows are launched ahead of larger vessels to screen against incoming missile volleys and probe enemy formations.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Sparrow",
                            Rarity = 0,
                            ShipHullClass = 0,
                            ShipProductionYear = 2235
                        },
                        new
                        {
                            Id = new Guid("3e9a4c7b-8f2d-4a56-b1c9-7d5e3a2f6b8c"),
                            Attack = 24,
                            Class = "Interceptor",
                            Defense = 2,
                            FleetId = new Guid("c8b02d34-76f8-4dbd-942e-2d680d5b84ef"),
                            Health = 120,
                            History = "The Vanguard was the first interceptor-class vessel produced by the Sol Shipyards in 2225. Originally designed for rapid reconnaissance missions, it quickly became the backbone of Alpha Fleet's patrol operations. Its lightweight frame and advanced sensor array made it ideal for early-warning deployments along the outer rim.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Vanguard",
                            Rarity = 1,
                            ShipHullClass = 1,
                            ShipProductionYear = 2225
                        },
                        new
                        {
                            Id = new Guid("2a6f1b8e-4d9c-4e3f-a5b2-c1d7e8f9a3b5"),
                            Attack = 56,
                            Class = "Corvette",
                            Defense = 6,
                            FleetId = new Guid("c8b02d34-76f8-4dbd-942e-2d680d5b84ef"),
                            Health = 280,
                            History = "The Harbinger is one of the oldest active vessels in the fleet, launched in 2215 from the Centauri Reach drydocks. It served as a testbed for experimental stealth technology and was instrumental in covert operations during the Vega Conflict.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = false,
                            Name = "Harbinger",
                            Rarity = 2,
                            ShipHullClass = 2,
                            ShipProductionYear = 2215
                        },
                        new
                        {
                            Id = new Guid("9c5b3d7e-6a1f-4c8a-b3d4-e9f2a5c6b8d1"),
                            Attack = 88,
                            Class = "Frigate",
                            Defense = 9,
                            FleetId = new Guid("4241c74f-092c-4249-b731-954fb7658830"),
                            Health = 440,
                            History = "The Aegis was designed as a defensive powerhouse, equipped with multi-layered shield generators and point-defence systems. Launched in 2230, it has served as the flagship escort for Beta Squadron across the Orion Sector.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Aegis",
                            Rarity = 0,
                            ShipHullClass = 3,
                            ShipProductionYear = 2230
                        },
                        new
                        {
                            Id = new Guid("7f4a9c2d-e3b1-4a7f-9d5c-2e8a4b6f1c9e"),
                            Attack = 288,
                            Class = "Destroyer",
                            Defense = 29,
                            FleetId = new Guid("4241c74f-092c-4249-b731-954fb7658830"),
                            Health = 1440,
                            History = "The Leviathan is a destroyer of unmatched firepower, completed in 2240 at the classified Sirius Gate facility. Its main battery can cripple a space station in a single salvo. Only one was ever built due to the immense cost.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = false,
                            Name = "Leviathan",
                            Rarity = 3,
                            ShipHullClass = 4,
                            ShipProductionYear = 2240
                        },
                        new
                        {
                            Id = new Guid("a1d4f8c3-5e2b-4d9a-8f1c-6a3e7b2f5d8a"),
                            Attack = 384,
                            Class = "Cruiser",
                            Defense = 38,
                            FleetId = new Guid("86634405-36a8-4727-93bd-97273e947361"),
                            Health = 1920,
                            History = "Commissioned in 2228, the Corsair was built to fill the gap between destroyers and heavy cruisers. Armed with quad plasma cannons and reinforced hull plating, it earned its reputation during the Orion Skirmishes where it held off an enemy flotilla for 72 hours.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Corsair",
                            Rarity = 1,
                            ShipHullClass = 5,
                            ShipProductionYear = 2228
                        },
                        new
                        {
                            Id = new Guid("d2b6f9a7-4c8e-4b3f-a1d5-9e7c2a5f8b1d"),
                            Attack = 704,
                            Class = "HeavyCruiser",
                            Defense = 70,
                            FleetId = new Guid("86634405-36a8-4727-93bd-97273e947361"),
                            Health = 3520,
                            History = "The Ironclad lives up to its name. Its hull is layered with seven centimetres of ablative armour plating, making it near impervious to light weapons fire. It has served as a forward assault vessel in every major fleet engagement since its commissioning.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Ironclad",
                            Rarity = 0,
                            ShipHullClass = 6,
                            ShipProductionYear = 2238
                        },
                        new
                        {
                            Id = new Guid("e8c3a5b9-6d2f-4a1e-9c7d-3f8b5a2e6c9a"),
                            Attack = 1792,
                            Class = "Battlecruiser",
                            Defense = 179,
                            FleetId = new Guid("86634405-36a8-4727-93bd-97273e947361"),
                            Health = 8960,
                            History = "The Nemesis was conceived as a warship that could hunt down and destroy anything short of a capital ship. Its long-range siege cannons can engage targets at distances that render enemy return fire nearly impossible.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Nemesis",
                            Rarity = 2,
                            ShipHullClass = 7,
                            ShipProductionYear = 2244
                        },
                        new
                        {
                            Id = new Guid("b4f7d1c8-9a3e-4d6b-a2f5-7e1c4b8d3a6f"),
                            Attack = 3072,
                            Class = "CapitalShip",
                            Defense = 307,
                            FleetId = new Guid("c8b02d34-76f8-4dbd-942e-2d680d5b84ef"),
                            Health = 15360,
                            History = "The Sovereign is the command vessel of the First Fleet, renowned across all sectors as a symbol of Sol's naval dominance. Its bridge houses a crew of four hundred officers, and its presence alone has ended conflicts before the first shot was fired.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Sovereign",
                            Rarity = 1,
                            ShipHullClass = 8,
                            ShipProductionYear = 2250
                        },
                        new
                        {
                            Id = new Guid("6c9e2d4a-7f1b-4c5a-b8e3-1d9a6f2c5b8e"),
                            Attack = 9216,
                            Class = "AircraftCarrier",
                            Defense = 922,
                            FleetId = new Guid("4241c74f-092c-4249-b731-954fb7658830"),
                            Health = 46080,
                            History = "The Colossus is the largest vessel ever constructed by humanity. Its cavernous flight deck houses over three hundred fighters and interceptors. It was built in secret over fifteen years at a classified Kuiper Belt facility, and its maiden deployment ended the Andromeda War in a single engagement.",
                            ImageUrl = "/images/ships/default.png",
                            IsAvailable = true,
                            Name = "Colossus",
                            Rarity = 3,
                            ShipHullClass = 9,
                            ShipProductionYear = 2255
                        });
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            Attack = 640,
                            Defense = 64,
                            Description = "A strategic outpost located in the Orion Sector, serving as a hub for fleet operations and logistics.",
                            Health = 6400,
                            ImageUrl = "/images/stations/orion_outpost.jpg",
                            IsDestroyed = false,
                            Location = "Orion Sector",
                            Name = "Orion Outpost"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7890-2345-6789abcdef01"),
                            Attack = 1280,
                            Defense = 128,
                            Description = "A heavily fortified station in the Vega System, known for its advanced defense systems and research facilities.",
                            Health = 12800,
                            ImageUrl = "/images/stations/vega_station.jpg",
                            IsDestroyed = false,
                            Location = "Vega System",
                            Name = "Vega Station"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7890-3456-789abcdef012"),
                            Attack = 320,
                            Defense = 32,
                            Description = "A remote station in the Centauri System, primarily used for deep-space exploration and scientific research.",
                            Health = 3200,
                            ImageUrl = "/images/stations/centauri_reach.jpg",
                            IsDestroyed = false,
                            Location = "Centauri System",
                            Name = "Centauri Reach"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-7890-4567-89abcdef0123"),
                            Attack = 2560,
                            Defense = 256,
                            Description = "A critical station located at the Sirius Gate, serving as a key transit point for fleet movements between sectors.",
                            Health = 25600,
                            ImageUrl = "/images/stations/sirius_gate.jpg",
                            IsDestroyed = false,
                            Location = "Sirius System",
                            Name = "Sirius Gate"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7890-5678-9abcdef01234"),
                            Attack = 5120,
                            Defense = 512,
                            Description = "A bustling station in the Andromeda Galaxy, known for its commercial activity and vibrant community of traders.",
                            Health = 51200,
                            ImageUrl = "/images/stations/andromeda_port.jpg",
                            IsDestroyed = false,
                            Location = "Andromeda Galaxy",
                            Name = "Andromeda Port"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Admiral", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.Fleet", "Fleet")
                        .WithOne("Admiral")
                        .HasForeignKey("AlphaFleet.Data.Models.Admiral", "FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Battle", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.Fleet", "AttackingFleet")
                        .WithMany()
                        .HasForeignKey("AttackingFleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaFleet.Data.Models.Fleet", "DefendingFleet")
                        .WithMany()
                        .HasForeignKey("DefendingFleetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlphaFleet.Data.Models.Station", "DefendingStation")
                        .WithMany()
                        .HasForeignKey("DefendingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttackingFleet");

                    b.Navigation("DefendingFleet");

                    b.Navigation("DefendingStation");
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.BattleTurn", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.Battle", "Battle")
                        .WithMany("BattleTurns")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Fleet", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Ship", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.Fleet", "Fleet")
                        .WithMany("Ships")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaFleet.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AlphaFleet.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Battle", b =>
                {
                    b.Navigation("BattleTurns");
                });

            modelBuilder.Entity("AlphaFleet.Data.Models.Fleet", b =>
                {
                    b.Navigation("Admiral");

                    b.Navigation("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
